### ISSUE TITLE
Cannot compile on Ubuntu 19.10 (lua.h not found)

### ISSUE THREAD

**Issue by hellocatfood** [agraef/pd-jacktime#2]
I'm trying to compile this on Ubuntu 19.10. I have installed:
* pd-lua - 0.7.3-2
* lua 5.3

When I run `make` I get the following error:
```
Package lua was not found in the pkg-config search path.
Perhaps you should add the directory containing `lua.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lua' found
cc -shared -fPIC -o jtime.so jtime.c -ljack 
jtime.c:20:10: fatal error: lua.h: No such file or directory
   20 | #include <lua.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:9: jtime.so] Error 1
```
I've done a system-wide search for lua.pc and have no results

**Comment by zigmhount** [comment]
It took me a bit of time to get it working too, so answering here for reference: lua itself is not enough, you need to install the development library of lua, e.g. on Debian with lua5.4 it's the package `liblua5.4-dev`.
Might be worth adding this to the Readme file :)

**Comment by agraef** [comment]
Thanks @zigmhount for the heads-up. I've reworked the README accordingly. Fixed in rev. 28d1124.
